### ISSUE TITLE
Errors in Dart on local dev server sometimes cause process termination

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/appengine#24]
When running the local development server, sometimes unhandled exceptions thrown from the dart code result in the development server process terminating rather logging an exception and returning an error 500.

This can result in unpleasant breaks in the development process, where the server suddenly disappears and if you're not actively watching the console output it can be sometime before you realise what has happened and restart it.

If this is unexpected, I'll attach a specific example next time I see it.

**Comment by zoechi** [comment]
This is default Docker behavior. When the process ends the docker container is shut down.

I use a customized Docker image with a customized `dart_runs.sh` file that just restarts the process if it exits. 

```bash
#!/bin/bash
#
# Copyright (c) 2014, the Dart project authors.  Please see the AUTHORS file
# for details. All rights reserved. Use of this source code is governed by a
# BSD-style license that can be found in the LICENSE file.

DBG_OPTION=
# Only enable Dart debugger if DBG_ENABLE is set.
if [ -n "$DBG_ENABLE" ] && [ "$GAE_PARTITION" = "dev" ] then
  echo "Enabling Dart debugger"
  DBG_OPTION="-c --debug:${DBG_PORT:-5858}/0.0.0.0"
  echo "Starting Dart with debug options $DBG_OPTION"
fi

if [ -n "$DART_VM_OPTIONS" ]; then
  echo "Starting Dart with additional options $DART_VM_OPTIONS"
fi

echo "/usr/bin/dart ${DBG_OPTION} --enable-vm-service:8181/0.0.0.0 ${DART_VM_OPTIONS} /app/bin/server.dart"

while true; do
  echo bin/server.dart
  /usr/bin/dart \
     ${DBG_OPTION} \
     --enable-vm-service:8181/0.0.0.0 \
     ${DART_VM_OPTIONS} \
     bin/server.dart
done
```

Could be worth adding to the default Docker images, but only when debug is enabled.

**Comment by mkustermann** [comment]
The fact that the uncaught exception is not surfaced to the developer is an issue of the AppEngine support in the GCloud SDK. Issues for it can be filed on the [AppEngine issue tracker](https://code.google.com/p/googleappengine/issues/list?can=2&q=Component%3DManagedVMs&colspec=ID+Type+Component+Status+Stars+Summary+Language+Priority+Owner+Log&cells=tiles) under the `Component=ManagedVMs` ?

Our `package:appengine` should catch all exceptions which happen **inside a request handler** and the dart server should still be alive. Errors are logged to the logging service (if the http response was not send before the error occured) and will also be printed to stdout ATM.

If there is an uncaught exception **outside of a request handler**, then the DartVM will die and prints uncaught exception error messages to stdout/stderr.

Again, the fact that stdout/stderr is not surfaced is caused by the GCloud SDK. You can get the information by running "gcloud --verbosity=debug preview app run app.yaml".

I'll let this bug open, for now, since we could have a debugging endpoint which shows uncaught request handler error messages in the browser, or send these errors to the user (if the http response wasn't written at the point in them when the error occurs).
=> Although this should normally be surfaced bye the AppEngine development server.

**Comment by mkustermann** [comment]
As explained above, all uncaught exceptions inside a request handler zone should be caught and reported via the logging service (please file a new issue if this is not the case)

Uncaught exceptions outside request handlers must be handled by the user.

It is now much easier to debug these issues locally because one can run apps locally also outside a docker container by directly launching it with `dart`.
