### ISSUE TITLE
Development server sometimes doesn't shut down cleanly

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/appengine#25]
Most of the time Ctrl + Cing the development server shuts down cleanly after purging etc. 

But sometimes it doesn't - it's not obvious what causes it to go one way or the other - this causes the dev server to keep hold of the ports its bound to, which causes the tedious ps, kill -9 ritual to be able to rebind.

Is there any more diagnostics data I can provide to help repro?

**Comment by zoechi** [comment]
For me it usually doesn't shut down properly. I created a start script that ensures the process is killed before it is restarted

```bash
#!/bin/bash
# kill older script if still running
if [ $(pgrep --exact -u ${USER} -f -c "/bin/bash tool/run.sh") -eq "2" ]; then
  pkill -SIGKILL --exact -u ${USER} -f -o "/bin/bash tool/run.sh"
fi

RUNNING_CONTAINER=`docker ps | grep my-app.default.dev1 | awk '{print $1}'`
if [ -n ${RUNNING_CONTAINER} ]; then
 docker stop ${RUNNING_CONTAINER}
fi

gcloud --verbosity debug preview app run app.yaml index.yaml
```
Maybe this helps as a workaround until the problem is fixed.

**Comment by mkustermann** [comment]
Mind filing a bug about this on the [AppEngine issue tracker](https://code.google.com/p/googleappengine/issues/list?can=2&q=Component%3DManagedVMs&colspec=ID+Type+Component+Status+Stars+Summary+Language+Priority+Owner+Log&cells=tiles) under the `Component=ManagedVMs` ?

This is not caused by the dart `package:appengine`, so there is not much we can do about it.
