### ISSUE TITLE
Unused versions seem to insisit on keep VMs alive

### ISSUE THREAD

**Issue by lukechurch** [dart-lang/appengine#26]
The auto-managed GAE instances seem to always spin up instances, even for versions that aren't in use.

To repro:

Create 2 versions of an app, setup traffic splitting => 4 vms as expected
Disable traffic splitting and route all traffic to the new version
Delete the VMs associated with the old version - they are get restarted again

However, if you delete the version, rather than just removing the traffic split the VMs can be removed.

I think I understand the rationale here, that the user could hit 2.foo.appspot.com which would need a serving version. However the side effect is that it causes 2*version count VMs to be lying around not doing anything, which carries a real $ cost. So it does make the multi-versions tools on AppEngine less appealing to use for development.

Could we consider using a 'lazy start' setting for versions, so that we could accept a much worse first-call performance in exchange for not keeping the VMs around for versions that aren't in active use?

**Comment by mkustermann** [comment]
To my knowledge this behavior is expected. You can control the scaling behavior via several settings in the `app.yaml` configuration file (e.g. via `manual_scaling`, `automatic_scaling`). See e.g. [here](https://cloud.google.com/appengine/docs/python/managed-vms/) for documentation.

The described behavior has nothing to do with the `package:appengine` package itself. So if the settings are not providing enough freedom for you it would be great if you could file a bug on the [AppEngine issue tracker](https://code.google.com/p/googleappengine/issues/list?q=component%3AManagedVMs)  with component being `Component-ManagedVMs`.

I'll close this issue, since it is not directly relevant for this repository.
