### ISSUE TITLE
https requests are coming through as http 

### ISSUE THREAD

**Issue by Andersmholmgren** [dart-lang/appengine#31]
Not sure where this originates. I am using shelf_appengine.

I can see from the logs and from some code that is doing an oauth dance to github and breaking as a result, that the requests are all hitting my app as http.

However, in the browser I can clearly see they are https. Also I have set up app.yaml to only allow https.

**Comment by mkustermann** [comment]
If you are using `request.requestedUri` then this issue should be fixed with the latest version.

Background: The `requestedUri` should be the URI the client used to connect to the server. But since there is a load balancer in between (and docker infrastructure) it appears to dart:io as if it came from non-https. Our `HttpRequest` wrapper in `package:appengine` should now interpret the `x-appengine-https` header correctly and modify `requestedUri` to be the correct URI used by the client.

Would you mind reporting back whether upgrading to the newest version fixed your issue?

**Comment by Andersmholmgren** [comment]
Thanks Martin. I'll let you know. Unfortunately I've completely fried docker at the moment so will need to fix that first somehow ;-)

**Comment by Andersmholmgren** [comment]
Hi Martin. Sorry for the delay. I can confirm this is working now. Thanks for the fix
