### ISSUE TITLE
Enviroment variables only passed by devappserver

### ISSUE THREAD

**Issue by KRIOFT** [dart-lang/appengine#51]
Hi,
I have a simple dart server for now. I can run it locally with ```dev_appserver.py --custom_entrypoint "dart bin/server.dart {port}" app.yaml```, but when I make ```gcloud app deploy``` i get an error ```Bad state: Expected docker environment variables not found.```.

After i search the the error is from ```...pub_packages_path.../appengine-0.3.3+1/lib/src/appengine_internal.dart``` function ```getDockerContext()``` and here is a comment ```TODO: [instance] is currently only passed by devappserver when starting docker container but not by real deployment.```

How can I run that dart server on appengine?

**Comment by mkustermann** [comment]
We have just released a new version of `package:appengine` which is compatibe with the new App Engine flexible environment.

Please try following the instructions in the new [readme](https://github.com/dart-lang/appengine/blob/master/README.md) file.

Since we no longer use `dev_appserver.py` I'll go ahead and close this issue.
