### ISSUE TITLE
Excessive log output when running appengine locally

### ISSUE THREAD

**Issue by enyo** [dart-lang/appengine#64]
I have upgraded to the latest appengine version, and when I now run my server, I get this log output for each request (and since I debug in Chromium, there are **a lot** of requests):

```
  2017-04-20 16:43:16.339561Z Debug: GET /packages/SOME_FILE
    Host: localhost
    User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.104 (Dart) Safari/537.36
    IP: 127.0.0.1
    -----------
    Http status: 200
    Response size: -1 bytes
    Request duration: 0:00:00.003827
    -----------
```

Is there a way to reduce this output?

**Comment by mkustermann** [comment]
Currently there is no way to reduce the output. The information printed mirrors what will be sent to the logging service when running in the cloud (it's intentionally pretty much the same information).

The only difference currently is that locally we print it for *every request* whereas in the cloud we only do it if there was at least one logging API call in the request handler.

Instead of adding more flags, we can just change the default behavior. Do you have a suggestion on what information you'd like to see (path, date, status, duration ...) and for which requests (or all)?

**Comment by enyo** [comment]
I think that the thing that is a bit problematic locally, is that it takes 9 lines of code when debugging, so normale debug information gets lost. So getting all that in one line would be ideal. Something like:

```
2017-04-20 16:43:16.339561Z GET 200 205ms /path/to/file 
```

I don't mind seeing all requests, when they only occupy one line.

**Comment by mkustermann** [comment]
So let's just do that - though still printing the user logging calls on a request basis. Something like this:
```
2017-04-24 08:27:50.445432Z GET 200 163 ms /items
      0 ms Info: app.main: handling request http://localhost:8080/items
    162 ms Info: app.main: sending json response
```

It's then up to the user to call `useLoggingPackageAdaptor()` or not.

**Comment by enyo** [comment]
Looks great!

**Comment by mkustermann** [comment]
This should be fixed in the latest version.

**Comment by enyo** [comment]
Thanks!
